### ISSUE TITLE
shift right click

### ISSUE THREAD

**Issue by mynian** [mynian/ConvertRatings#13]
Copy/Paste from curse

Get this error when shift-right clicking artifact:
 
101x ConvertRatings\ConvertRatings-1.9.1.lua:147: Usage: GetItemInfo(itemID|"name"|"itemlink")
[C]: in function `GetItemInfo'
ConvertRatings\ConvertRatings-1.9.1.lua:147: in function <ConvertRatings\ConvertRatings.lua:116>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetCompareItem'
FrameXML\GameTooltip.lua:366: in function `GameTooltip_ShowCompareItem'
FrameXML\EquipmentFlyout.lua:587: in function `EquipmentFlyoutButton_UpdateTooltip'
FrameXML\EquipmentFlyout.lua:399: in function `UpdateTooltip'
FrameXML\EquipmentFlyout.lua:471: in function <FrameXML\EquipmentFlyout.lua:469>

Locals:
(*temporary) = nil

**Comment by mynian** [comment]
can not reproduce, please check to see if you have another addon that is causing a conflict.

**Comment by derickso** [comment]
Looks like an issue with this mod and Can I Mog It?

**Comment by mynian** [comment]
installed Can I Mog It? 

It seems to be an issue when the "debug tooltip" option is enabled and the shift button is pressed while hovering over an artifact, not actually the click. It probably has something to do with the way can i mog it modifies the tooltip of the item when its shown in the compare tooltip. 

This did bring to light another issue with artifacts that I discovered, which isn't too pressing but I will open up an issue for it to show it as known.

**Comment by derickso** [comment]
It happens to me without debug tooltip selected, just having both installed with no CIMI options selected produces the error

**Comment by mynian** [comment]
That's weird, because I do not get any errors with the out of the box settings for the other addon.
