### ISSUE TITLE
Apparent conflict with non-standard tooltips

### ISSUE THREAD

**Issue by MightBeChris** [mynian/ConvertRatings#16]
Not really an issue, so much as an annoyance.  Can't mouse over a few random things without throwing this error:

Message: ConvertRatings\ConvertRatings-1.10.5a.lua:147: Usage: GetItemInfo(itemID|"name"|"itemlink")
Stack: [C] in function 'GetItemInfo'
ConvertRatings\ConvertRatings-1.10.5a.lua:147: in function <ConvertRatings\ConvertRatings.lua:116>
[C] ?
[C] ?
[C] ?
...dOns\HiddenArtifactTracker\HiddenArtifactTracker.lua:133: in function <...dOns\HiddenArtifactTracker\HiddenArtifactTracker.lua:130>
[C] ?
[C] ?
[C] ?
...rface\TradeSkillMaster\Private\TooltipLib.lua:85: in function <...rface\TradeSkillMaster\Private\TooltipLib.lua:82>
[C] ?
[C] ?
[C] ?
[C] in function 'SetToyByItemID'
AutoBar\AutoBarClassBasicButton.lua:69: in function 'TooltipShow'
AutoBar\AutoBarClassPopupButton.lua:62: in function <AutoBar\AutoBarClassPopupButton.lua:55>
[C] ?
FrameXML\SecureHandlers.lua:264: in function <FrameXML\SecureHandlers.lua:261>
[C] ?
FrameXML\SecureHandlers.lua:320: in function <FrameXML\SecureHandlers.lua:304>
(tail call): ?
Time: 2017/06/16 12:58:39 Count: 2
Locals:
(*temporary) = nil

As it has to do with displays inside other addon's tooltips I assume it's ConvertRating not knowing what to do with specific info those addons generate.  Is this something I should forward to each addon author or is it your wheelhouse?

**Comment by mynian** [comment]
I've had a few others report similar issues with other addons, and I have no idea on what causes it.

The error that is being thrown is from when my addon attempts to grab the itemid from whatever is moused-over. Something with the way certain addons are coded is preventing the itemid being passed correctly ... for whatever reason.

This is similar to #13 #12 #11

**Comment by mynian** [comment]
if you could, please update to the latest beta version and see if issue still persists

**Comment by mynian** [comment]
@MightBeChris have you had a chance to test?

**Comment by MightBeChris** [comment]
I am so sorry....I just noticed you'd sent me a reply.  I haven't yet, but I just updated and will try to remember to get back to you.

**Comment by MightBeChris** [comment]
Look, I'm not really into keeping up with other humans.  It's kinda not anything I pay attention too.  So please don't expect actual effort in communicating.  But the issue still persists.  It's not quite as common, but still borks up every now and then.

Here's the latest bug report it's thrown: 
x9  ConvertRatings\ConvertRatings-1.11.lua:257: bad argument #1 to 'find' (string expected, got nil)
Stack: [C] in function 'find'
ConvertRatings\ConvertRatings-1.11.lua:257: in function <ConvertRatings\ConvertRatings.lua:116>
[C] ?
...dOns\HiddenArtifactTracker\HiddenArtifactTracker.lua:136: in function <...dOns\HiddenArtifactTracker\HiddenArtifactTracker.lua:133>
[C] ?
[C] ?
[C] ?
[C] ?
[C] ?
[C] ?
...rface\TradeSkillMaster\Private\TooltipLib.lua:85: in function <...rface\TradeSkillMaster\Private\TooltipLib.lua:82>
[C] ?
[C] ?
...face\AdiBags\libs\AceHook-3.0\AceHook-3.0-8.lua:95: in function <...face\AdiBags\libs\AceHook-3.0\AceHook-3.0.lua:87>
[C] ?
...rface\TradeSkillMaster\Private\TooltipLib.lua:95: in function <...rface\TradeSkillMaster\Private\TooltipLib.lua:93>
[C] ?
[C] in function 'SetBagItem'
FrameXML\ContainerFrame.lua:1149: in function 'ContainerFrameItemButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>
Time: 2017/08/06 11:12:06 Index: 1/1
Locals:
(*temporary) = nil
(*temporary) = "Critical Strike"
(*temporary) = "string expected, got nil"
