### ISSUE TITLE
Incorrect stats rating for arms/fury warrior artifact

### ISSUE THREAD

**Issue by TristonQ** [mynian/ConvertRatings#19]
Arms artifact shows 1 critical strike rating and 1 mastery rating: 
![image](https://user-images.githubusercontent.com/5865233/33811772-145df9c0-de6b-11e7-9239-dc966addd074.png)

Fury artifact shows 1 critical strike rating and 1 mastery rating as well: 
![image](https://user-images.githubusercontent.com/5865233/33811791-4878a070-de6b-11e7-8e77-18d9acb8eb5e.png)

However, protection warrior artifact shows correct critical strike rating and mastery rating :
![image](https://user-images.githubusercontent.com/5865233/33811801-5cd95866-de6b-11e7-888d-1995a498b6d4.png)

**Comment by mynian** [comment]
I just tested on my warrior. I did not encounter this error. My best guess is that the client language is affecting it somehow.

**Comment by Llamatron2112** [comment]
I'm using english client, and I have this problem too, some ratings on artifacts show as 1 (for example both on the affliction lock, and one of the marksman hunter)

**Comment by Neralus** [comment]
I'm having the same issue. noticed it on frost mage artifact.
After checking other artifacts it seems to me that every second stat on an artifact that is higher 1000 will be shown as 1

**Comment by mynian** [comment]
Ok with that little tidbit of info maybe i can track down the issue. I will look into it and see what i can find.

**Comment by mynian** [comment]
This issue was caused by the pattern matching logic I was using to grab the values on the artifact weapons. It was only grabbing the numbers before punctuation and leaving everything else off, so that's why it was showing as a 1 for values over 1000.
