### ISSUE TITLE
Error when mousing over artifact weapon

### ISSUE THREAD

**Issue by jrhz** [mynian/ConvertRatings#21]
When mousing over my artifact weapon on Blood DK or Prot Pally (probably others, just confirmed these two), I get a Lua Error:

```Message: Interface\AddOns\ConvertRatings\ConvertRatings.lua:177: attempt to index local 'rawspeed' (a nil value)
Time: 02/18/18 13:13:33
Count: 2
Stack: Interface\AddOns\ConvertRatings\ConvertRatings.lua:177: attempt to index local 'rawspeed' (a nil value)
Interface\SharedXML\SharedBasicControls.lua:208: in function <Interface\SharedXML\SharedBasicControls.lua:207>
[C]: ?
Interface\AddOns\ConvertRatings\ConvertRatings.lua:177: in function <Interface\AddOns\ConvertRatings\ConvertRatings.lua:116>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetInventoryItem'
Interface\FrameXML\PaperDollFrame.lua:1637: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals: errorMessage = "Interface\AddOns\ConvertRatings\ConvertRatings.lua:177: attempt to index local 'rawspeed' (a nil value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:191
MESSAGE_TYPE_ERROR = 0
```

**Comment by mynian** [comment]
I just tried on my Prot pally and did not get any errors. I switched over to a character that has speed on an item to see if the variable wasn't getting ignored properly when you previously moused over an item with speed prior to mousing over your artifact weapon, and still did not get an error.

Can you please try again with all other addons disabled and see if the issue persists?

**Comment by jrhz** [comment]
Ah, so the issue is that I have an equipment set called "Blood Speed" which triggers the error. If I rename the set to something else (including just plain "speed" with a lower case s) it stops triggering.

**Comment by mynian** [comment]
interesting .... I'll see if there is a way that I can get it to ignore the line that gets added to tooltips when you save item sets

**Comment by mynian** [comment]
fixed in next release
