### ISSUE TITLE
errors when mousing over Azerite armor

### ISSUE THREAD

**Issue by Seclipse99** [mynian/ConvertRatings#23]
recently getting errors when hover over Azerite armor. 
317x ConvertRatings\ConvertRatings-1.14.1.lua:292: bad argument #1 to 'find' (string expected, got nil)
[C]: in function `find'
ConvertRatings\ConvertRatings-1.14.1.lua:292: in function <ConvertRatings\ConvertRatings.lua:116>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:482: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:476>
[C]: ?
[C]: ?
[C]: ?
Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:408: in function <Auc-Advanced\Libs\LibExtraTip\LibExtraTip.lua:402>
[C]: ?
[C]: in function `SetInventoryItem'
FrameXML\PaperDollFrame.lua:1677: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Critical Strike"
(*temporary) = "string expected, got nil"

**Comment by mynian** [comment]
Do you have an auction type addon installed?

If you do please disable it and see if the error persists.

**Comment by Seclipse99** [comment]
i disabled auctioneer, then the errors referenced Convert ratings and Informant, disabled informant also and this is now the error i get when hovering over azerite armor.

331x ConvertRatings\ConvertRatings-1.14.1.lua:292: bad argument #1 to 'find' (string expected, got nil)
[C]: in function `find'
ConvertRatings\ConvertRatings-1.14.1.lua:292: in function <ConvertRatings\ConvertRatings.lua:116>
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: ?
[C]: in function `SetInventoryItem'
FrameXML\PaperDollFrame.lua:1677: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = nil
(*temporary) = "Critical Strike"
(*temporary) = "string expected, got nil"

**Comment by mynian** [comment]
Can you take a screenshot of the item tooltip you are hovering over when you get the error?

I haven't experienced this error myself so seeing the item data will help track this down. I have an idea of what is causing it.

**Comment by Seclipse99** [comment]
![wowerror](https://user-images.githubusercontent.com/42900552/44952031-95da8200-ae42-11e8-9a37-d8b0757e8c48.JPG)

after seeing your comment i disabled "Azerite Tooltip" and all errors stopped. it seems after the last update to the azerite tool tip addon it now conflicts your your addon. the errors only happen on azerite armor of anytype and nothing else. 
sorry for jumping the gun and listing it as a issue on your addon, my error filter listed it as a problem with convert ratings.

**Comment by mynian** [comment]
Not a problem. Thanks for the update.

**Comment by Seclipse99** [comment]
just an update, the owner of Azerite tool tips responded to this conflict with a temporary fix and it does indeed stop the errors.
Jokair9-
Hmmm i don't really know why this conflict triggers. You can fix it by adding this at line 290 on ConvertRatings.
if C_AzeriteEmpoweredItem.IsAzeriteEmpoweredItemByID(itemLink) then return end
I'll look more into it to see if I can fix anything on my side.

**Comment by mynian** [comment]
That stops the errors, because it turns off the functionality of the addon on azerite items, which I guess isn't that big of an issue since azerite items don't have secondary stats.

**Comment by mynian** [comment]
Actually, that line only stops the error if the error is caused by the other addon passing a nil to "Critical Strike" not all secondary stats.
