### ISSUE TITLE
Global error occurring after update to 8.1.5

### ISSUE THREAD

**Issue by Ookami313** [mynian/ConvertRatings#24]
Receiving the following error after updating to 8.1.5 and logging into the game. Thanks.

Date: 2019-03-12 21:28:19
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\ConvertRatings\ConvertRatings.lua line 373:
   attempt to index global 'WorldMapTooltip' (a nil value)
Debug:
   ConvertRatings\ConvertRatings.lua:373: in main chunk
Locals:
colorTable = <table> {
 blue = <table> {
 }
 lightred = <table> {
 }
 pink = <table> {
 }
 default = <table> {
 }
 white = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 purple = <table> {
 }
 lightblue = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
}
myColorCallback = <function> defined @Interface\AddOns\ConvertRatings\ConvertRatings.lua:31
mathround = <function> defined @Interface\AddOns\ConvertRatings\ConvertRatings.lua:73
masteryamt = nil
critamt = nil
hasteamt = nil
versinamt = nil
versoutamt = nil
leechamt = nil
avoidamt = nil
speedamt = nil
getItemIdFromTooltip = <function> defined @Interface\AddOns\ConvertRatings\ConvertRatings.lua:116
(*temporary) = nil
(*temporary) = "ItemTooltip"
(*temporary) = true
(*temporary) = nil
(*temporary) = <function> defined @Interface\FrameXML\GameTooltip.lua:555
(*temporary) = 9.696985
(*temporary) = 11.117559
(*temporary) = 12.746242
(*temporary) = 14.613522
(*temporary) = 16.754351
(*temporary) = 20
(*temporary) = 2.735463
(*temporary) = 2.773512
(*temporary) = 2.812278
(*temporary) = 2.851772
(*temporary) = 2.892010
(*temporary) = 2.933004
(*temporary) = 2.974770
(*temporary) = 3.017321
(*temporary) = 3.060672
(*temporary) = 3.104839
(*temporary) = 3.149836
(*temporary) = 3.195680
(*temporary) = 3.242387
(*temporary) = 3.289971
(*temporary) = 3.338451
(*temporary) = 3.387843
(*temporary) = 3.438164
(*temporary) = 3.489431
(*temporary) = 3.541662
(*temporary) = 3.594877
(*temporary) = 3.649091
(*temporary) = 3.704326
(*temporary) = 3.760600
(*temporary) = 3.817932
(*temporary) = 3.876343
(*temporary) = 3.935852
(*temporary) = 3.996481
(*temporary) = 4.058250
(*temporary) = 4.121180
(*temporary) = 4.185295
(*temporary) = "attempt to index global 'WorldMapTooltip' (a nil value)"

AddOns:

**Comment by Malledeto** [comment]
A workaround can be made.

In line 373, change WorldMapTooltip for GameTooltip.
(WorldMapTooltip has been deprecated in 8.5.1)
BTW uploaded the modified files here.
[ConvertRatings.zip](https://github.com/mynian/ConvertRatings/files/3016805/ConvertRatings.zip)

**Comment by mynian** [comment]
Fixed in latest release
