### ISSUE TITLE
The following error occurred recently

### ISSUE THREAD

**Issue by BlueNightSky** [mynian/ConvertRatings#26]
The following error occurred recently:
`9x ConvertRatings\ConvertRatings-2.0.1.lua:426: attempt to perform arithmetic on local 'eqstvers' (a nil value)
[string "@ConvertRatings\ConvertRatings-2.0.1.lua"]:426: in function <ConvertRatings\ConvertRatings.lua:214>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@!Ace3\AceHook-3.0\AceHook-3.0-9.lua"]:95: in function <!Ace3\AceHook-3.0\AceHook-3.0.lua:87>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetAction'
[string "@Bartender4\libs\LibActionButton-1.0\LibActionButton-1.0-80.lua"]:1535: in function `SetTooltip'
[string "@Bartender4\libs\LibActionButton-1.0\LibActionButton-1.0-80.lua"]:1302: in function <...er4\libs\LibActionButton-1.0\LibActionButton-1.0.lua:1295>
[string "@Bartender4\libs\LibActionButton-1.0\LibActionButton-1.0-80.lua"]:519: in function <...er4\libs\LibActionButton-1.0\LibActionButton-1.0.lua:517>

Locals:
self = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 SetPvpTalent = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @TinyTooltip\Core.lua:858
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 style = <unnamed> {
 }
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 4
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetCurrencyTokenByID = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined =[C]:-1
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 updateTooltip = 0.154000
 SetCompanionPet = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 shownMoneyFrames = 2
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 backdropInfo = <table> {
 }
 SetCurrencyByID = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 0 = <userdata>
 Hide = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetMerchantItem = <function> defined =[C]:-1
 SetArtifactPowerByID = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 TopRightCorner = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 SetSpellByID = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @TinyTooltip\Core.lua:859
 GetBackdrop = <function> defined @TinyTooltip\Core.lua:857
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 SetToyByItemID = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 comparing = false
 TopLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 SetTrainerService = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 SetTradeTargetItem = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetRecipeRankInfo = <function> defined =[C]:-1
 BottomEdge = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 model = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined @ShinyBuffs\ShinyBuffs.lua:219
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
 Center = <unnamed> {
 }
 BigFactionIcon = <unnamed> {
 }
 SetRecipeResultItem = <function> defined =[C]:-1
}
name = ""
itemLink = "|cff0070dd|Hitem:180116::::::::60:263::1:4:6805:40:1472:4785:1:28:2044:::|h[超載的靈魄電池]|h|r"
rawcrit = nil
rawhaste = nil
rawmastery = nil
rawvers = nil
stats = <table> {
 ITEM_MOD_CR_AVOIDANCE_SHORT = 30
 ITEM_MOD_AGILITY_SHORT = 41
}
rawl`

**Comment by trinketeer** [comment]
Im not trained in any coding but Id suspect the formatting seen in 9.0.2
'obsoletefied' ("not active in shadowlands") gear tooltips is aggressive
enough of a change to ConvertRatings' backyard that , while trying to
refurbish the fence between it & that neighbor, the addon accidentally
divides by zero instead of "hero" and thus Shadowlands is reached

Cheers

**Comment by mynian** [comment]
So this error is throwing stuff referencing Ace functions. I don't use any Ace functions in my code. I see references to the addons Bartender, ShinyBuffs, and TinyTooltip. Try disabling those one by one and see if the error persists.

**Comment by mynian** [comment]
Shiny Buffs hasn't been updated for Shadowlands, so I'm thinking that may be the culprit.

**Comment by BlueNightSky** [comment]
I am traveling now and will not be home until tomorrow. I will try to close Shiny Buffs and see if there are any errors. thanks！

I tried to disable ShinyBuffs and TinyTooltip, the same error still appears, but the frequency is relatively low.

**Comment by Ookami313** [comment]
Currently running 2.0.2 and I just noticed this error when I moused over a trinket in my character sheet. The error also occurred when I moused over a trinket in my bags.
Taking a page from your comment above I noticed that TradeSkillMaster, SetCollector, and Vendor were listed in my version of the error, so I disabled all three; error still occurs. However, the error only seems to occur on my Horde character. I logged into my Alliance character and no error occurred when I moused over one of their trinkets. 

21x ConvertRatings\ConvertRatings-2.0.2.lua:426: attempt to perform arithmetic on local 'eqstvers' (a nil value)
[string "@ConvertRatings\ConvertRatings-2.0.2.lua"]:426: in function <ConvertRatings\ConvertRatings.lua:214>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `?'
[string "@SetCollector\Tooltips.lua"]:116: in function <SetCollector\Tooltips.lua:52>
[string "=[C]"]: ?
[string "=[C]"]: ?
...
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:98: in function <...Master\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@Vendor\sys\hook.lua"]:95: in function <Vendor\sys\hook.lua:91>
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML\PaperDollFrame.lua"]:1660: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
self = GameTooltip {
 0 = <userdata>
 SetText = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 SetVoidWithdrawalItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 SetSocketGem = <function> defined =[C]:-1
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 Show = <function> defined =[C]:-1
 default = 1
 SetLFGDungeonReward = <function> defined @AllTheThings\AllTheThings.lua:4990
 FadeOut = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 TopRightCorner = <unnamed> {
 }
 ttIcon = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 updateTooltip = 0.128000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 ttCount = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetAuctionSellItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 hasMoney = 1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 SetAuctionItem = <function> defined =[C]:-1
 shownMoneyFrames = 1
 SetCurrencyByID = <function> defined @AllTheThings\AllTheThings.lua:4944
 SetQuestLogItem = <function> defined =[C]:-1
 comparing = false
 CIMI_tooltipWritten = false
 SetTrainerService = <function> defined =[C]:-1
 AttachComplete = true
 textLeft1Font = "GameTooltipHeaderText"
 AllTheThingsProcessing = true
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:725
 SetGuildBankItem = <function> defined =[C]:-1
 SetVoidItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 TopLeftCorner = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 SetOwner = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetIconTextureAndText = <function> defined @TipTacItemRef\ttItemRef.lua:62
 textRight2Font = "GameTooltipText"
 BottomEdge = <unnamed> {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 SetUnitBuff = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 SetToyByItemID = <function> defined =[C]:-1
 ttGradient = <unnamed> {
 }
 SetMerchantCostItem = <function> defined =[C]:-1
 SetInboxItem = <function> defined =[C]:-1
 SetVoidDepositItem = <function> defined @TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua:96
 TextLeft1 = GameTooltipTextLeft1 {
 }
 BottomLeftCorner = <unnamed> {
 }
 SetLFGDungeonShortageReward = <function> defined @AllTheThings\AllTheThings.lua:5007
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 SetTradeTargetItem = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 HasBackdropInfo = <function> defined

**Comment by rstuke82** [comment]
Getting same error too.  It is not showing % on my rings or trinkets.  

11x ConvertRatings\ConvertRatings-2.0.2.lua:426: attempt to perform arithmetic on local 'eqstvers' (a nil value)
[string "@ConvertRatings\ConvertRatings-2.0.2.lua"]:426: in function <ConvertRatings\ConvertRatings.lua:214>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML\PaperDollFrame.lua"]:1660: in function `PaperDollItemSlotButton_OnEnter'
[string "*:OnEnter"]:1: in function <[string "*:OnEnter"]:1>

Locals:
self = GameTooltip {
 BottomLeftCorner = <unnamed> {
 }
 SetText = <function> defined =[C]:-1
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:195
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:433
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:325
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 2
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:257
 BottomOverlay = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:231
 updateTooltip = 0.178000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:442
 LeftEdge = <unnamed> {
 }
 ZGV_ShowManyLines = <function> defined @ZygorGuidesViewer\Functions.lua:353
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:725
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:465
 TextRight1 = GameTooltipTextRight1 {
 }
 BottomEdge = <unnamed> {
 }
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:372
 shownMoneyFrames = 1
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:452
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:390
 SetUnitDebuff = <function> defined =[C]:-1
 SetItemByID = <function> defined =[C]:-1
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:321
 SetQuestItem = <function> defined =[C]:-1
 comparing = false
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:309
 SetToyByItemID = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:337
 SetInboxItem = <function> defined =[C]:-1
 SetBackpackToken = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetCurrencyTokenByID = <function> defined =[C]:-1
 0 = <userdata>
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:225
 SetTradeTargetItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 StatusBar = GameTooltipStatusBar {
 }
 ItemTooltip = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 TopLeftCorner = <unnamed> {
 }
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined =[C]:-1
 TextLeft1 = GameTooltipTextLeft1 {
 }
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:289
 backdropInfo = <table> {
 }
 TopRightCorner = <unnamed> {
 }
 SetRecipeResultItem = <function> defined @Altoholic\Tooltip.lua:725
}
name = "Ritual Bone Band"
itemLink = "|cff0070dd|Hitem:178870:6167:::::::60:264::1:5:6805:6652:7194:1472:4785:1:28:2044:::|h[Ritual Bone Band]|h|r"
rawcrit = nil
rawhaste = nil
rawmastery = 32
rawvers = 71
stats = <table> {
 ITEM_MOD_MASTERY_RATING_SHORT = 32
 ITEM_MOD_VERSATILITY = 71
 ITEM_MOD_STAMINA_SHORT = 39
}
rawleech = nil
rawavoid = nil
rawspeed = nil
hexcolor = nil
oldmastery = 266
newsomastery = 234
newstmastery = nil
oldcrit = 235
newsocrit = nil
newstcrit = 183
oldhaste = 325
newsohaste = nil
newsthaste = 252
oldvers = 334
newsovers = 263
newstvers = nil
oldavoid = 52
newsoavoid = nil
newstavoid = nil
oldspeed = 0
newsospeed = nil
newstspeed = nil
old

**Comment by mynian** [comment]
So I think I found the error, hopefully this should be resolved in v2.0.3

**Comment by mynian** [comment]
well not v2.0.3, but hopefully v2.0.4 fixes it
