### ISSUE TITLE
Double Converted ratings on fingers

### ISSUE THREAD

**Issue by Dathwada** [mynian/ConvertRatings#28]
![0ad3fdac19](https://user-images.githubusercontent.com/57680823/102696101-24e65080-422c-11eb-97b9-a0a8bef8b3a7.jpg)

**Comment by mynian** [comment]
Not a bug. That is showing you what percentages you would get on each slot. They would show different percentages if replacing one of the slots would put you in a different diminishing returns bracket for that given stat.
