### ISSUE TITLE
Tooltip conversion of "Stone Legion Heraldry" Trinket 

### ISSUE THREAD

**Issue by Tubbymurra** [mynian/ConvertRatings#29]
There seems to be a problem when the addon converts this trinket effect into versatility. My character is getting +91 Vers, not the +50 reported. 

With addon
![With addon](https://user-images.githubusercontent.com/76542080/103049003-52414000-4545-11eb-9faf-d827ddafa28b.png)
Without addon
![Without addon](https://user-images.githubusercontent.com/76542080/103049016-58cfb780-4545-11eb-8501-41b04b5eb96d.png)

**Comment by mynian** [comment]
interesting, as the addon should not be capturing the versatility in that line. Will investigate.

**Comment by mynian** [comment]
well the way that trinket is coded to present it's stats is weird. I think they must have made a change to the trinket at some point from a straight vers bonus to that fancy on equip buff and forgot to change some backend code. I figured out how to ignore that line and will work on getting a fix out.

**Comment by mynian** [comment]
should be fixed in latest release

**Comment by Tubbymurra** [comment]
Looks good, thanks for the quick fix. Hope you had a great day/holiday.
