### ISSUE TITLE
Are two sets of the output really useful?

### ISSUE THREAD

**Issue by LordRomzessV** [mynian/ConvertRatings#30]
Are there real-world examples where double stats on rings and trinkets are useful? I have been looking at these numbers from the start of the add-on and in 3 months I have never come across different values. But at the same time, the hints for items with versatility are too wide due to the long hint line.

**Comment by mynian** [comment]
The only time you would see a difference in value would be if one of the slots puts you into a different stat DR break point than the other slot does.

Its the only way that I could think of to allow you to accurately see what you would be getting when this situation occurs.

**Comment by LordRomzessV** [comment]
It is impossible to make some function that will check the values and, if they are equal, hide the second set?

**Comment by mynian** [comment]
Impossible? No.
Time consuming to rewrite? Yes
