### ISSUE TITLE
Pretty sure this is your addon

### ISSUE THREAD

**Issue by ZINK-ZINK** [mynian/ConvertRatings#33]
![Ratings Addon Bug](https://user-images.githubusercontent.com/96964163/184530150-f2a054f9-6159-46b6-a035-dee47d2ddb90.png)

**Comment by ZINK-ZINK** [comment]
Oh, and there is no error or bug to paste for you. I've had those gloves for days, but it just occurred to me they AREN'T named "+62 SPEED"; I thought it was a silly mechagon thing.

**Comment by mynian** [comment]
Why in the fuck would blizzard code a name to use the stat name localization shortcut .........

I'll see if I can figure out how to bypass that.

**Comment by mynian** [comment]
should be fixed in latest release
