### ISSUE TITLE
Other half of tooltip weirdness still

### ISSUE THREAD

**Issue by ZINK-ZINK** [mynian/ConvertRatings#35]
LOL at your comment on my last Issue post here, you're my kind of angry dev! You did fix most of the bug, but apparently the 2nd tooltip still does it. Thanks though!

![Ratings Bug 2](https://user-images.githubusercontent.com/96964163/184735147-be878927-e597-471d-9c33-e3271277c421.png)

**Comment by mynian** [comment]
FFS ..... Apparently my quick fix of just ignore the first line of the tooltip wasn't duct-tapey enough ..... Guess I'll have to get it to ignore the second line too ....

**Comment by ZINK-ZINK** [comment]
To be fair it's such an edge-case bug if it becomes a stubborn one too I just wouldn't worry about it. There's probably only a single digit number of people who will even encounter the bug in its current form. And it doesn't even throw out errors ever, it just is.

**Comment by mynian** [comment]
I mean it will be an easy fix once I get back to my PC .... I will literally just have to change the ignore function line from, if tooltip line number is 1 to if tooltip line number is less than or equal to 2

**Comment by ZINK-ZINK** [comment]
ah well that's good then. It sounded like it would be a lot of trouble or annoying. I couldn't code to save my life, I'm a hardware type of geek.

**Comment by mynian** [comment]
New Release, should be fixed.
