### ISSUE TITLE
Support for Dragonflight

### ISSUE THREAD

**Issue by Lor4de** [mynian/ConvertRatings#36]
Hey, thank you for your great Addon. Do you have any plans to continue the development for the upcoming release of Dragonflight?

**Comment by mynian** [comment]
Has it stopped working?

**Comment by Lor4de** [comment]
No currently its working without any flaw, i was just curious because your addon is one of the last must-have addons for me, which didnt get any code/toc update after the pre patch release

**Comment by mynian** [comment]
I released a new version that should support 10.0 and level 70.

**Comment by Lor4de** [comment]
Thank you :)
