### ISSUE TITLE
Ratings not converting in tool tip

### ISSUE THREAD

**Issue by dewson8** [mynian/ConvertRatings#38]
Also when I type in the /cvr or /convertratings no options menu appears. Listed below are the errors i'm getting in my bugsack.

error 1:
1x Interface/AddOns/ConvertRatings/ConvertRatings.lua:2169: '<eof>' expected near 'end'

Locals:

error 2:
1x Interface/AddOns/ConvertRatings/ConvertRatings.lua:1 Interface/AddOns/ConvertRatings/ConvertRatings.lua:2169: '<eof>' expected near 'end'

error 3:
1x FrameXML\Bindings.xml:1 Interface/AddOns/ConvertRatings/ConvertRatings.lua:1 Interface/AddOns/ConvertRatings/ConvertRatings.lua:2169: '<eof>' expected near 'end'

**Comment by Dathwada** [comment]
Delete in ConvertRatings.lua in line 1771 the `end` and it should work again (until the Author releases an update to fix this)

**Comment by mynian** [comment]
Deleting random "end"s is not the way to fix it.

I just reverted my local file to the last stable build, and then re-added the new calcs for DF. 

Apparently the lines that I thought that got mysteriously deleted, got moved to a different part of the calculation so when I re-added them to the file it just fucked everything up even more.

Releasing a new patch.

**Comment by dewson8** [comment]
i'll just wait for the new release to come out. thanks for the response!

**Comment by mynian** [comment]
Also, I do not have a options menu. /cvr should just print the config instructions to the chat panel

**Comment by Dathwada** [comment]
It is actually not just an random end. This end closed your getItemIdFromTooltip function.

**Comment by mynian** [comment]
Its irrelevant at this point since the latest update fixed everything, but one of the lines that got mysteriously moved around (when I originally thought they got deleted) included an end, so when I added those lines back to where they should have been, without knowing that they were moved, an extra end was added, so it started closing functions, logic checks, loops, etc way too early.
