### ISSUE TITLE
Conversions only showing on "compared items"

### ISSUE THREAD

**Issue by dewson8** [mynian/ConvertRatings#39]
I completely deleted all old versions and WTF files for the previous versions and clean installed the newest release and i'm running into this issue. It is no longer throwing any error codes but the conversions are not showing up on the tooltips of whatever i'm hovering over. It will, however show the conversions on the compared "equipped" item as shown in these screen shots attached.
<img width="336" alt="Screenshot_20221101_060805" src="https://user-images.githubusercontent.com/101888532/199150588-e99a6587-b0f5-4289-b262-2f0edecffd0b.png">
<img width="444" alt="Screenshot_20221101_060904" src="https://user-images.githubusercontent.com/101888532/199150600-6e0af0e4-f3df-48d8-bfe5-9640262fc623.png">

**Comment by mynian** [comment]
You most likely have another addon that is preventing the numbers from showing up. I logged into WoW with only this addon loaded and am having no issues.

**Comment by dewson8** [comment]
i don't see how that would be the case as it had worked all the way up until the recent break and i have not downloaded any new addons.

**Comment by mynian** [comment]
¯\\\_(ツ)_/¯

I just got home and logged into my main computer, with all of the other addons I use on a daily basis and it works just fine. I would recommend turning off your other addons one at a time and see if it that allows it to work.

![image](https://user-images.githubusercontent.com/11283552/199389024-ac127582-8399-4c0b-a9f7-038d26b29399.png)
