### ISSUE TITLE
Lua error - WeakAura conflict

### ISSUE THREAD

**Issue by BlueNightSky** [mynian/ConvertRatings#43]
There was an error when I first logged in: (v2.3.0)
`1x Interface/AddOns/ConvertRatings/ConvertRatings.lua:2027: attempt to index local 'line' (a nil value)
[string "@Interface/AddOns/ConvertRatings/ConvertRatings.lua"]:2027: in function <Interface/AddOns/ConvertRatings/ConvertRatings.lua:228>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=(tail call)"]: ?
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:3377: in function <Interface/AddOns/WeakAuras/GenericTrigger.lua:3376>
[string "@Interface/AddOns/WeakAuras/GenericTrigger.lua"]:3419: in function `func'
[string "@Interface/AddOns/!Ace3/AceTimer-3.0-17/AceTimer-3.0.lua"]:57: in function <Interface/AddOns/!Ace3/AceTimer-3.0/AceTimer-3.0.lua:50>

Locals:
self = WeakAurasTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 shouldRefreshData = true
 SetSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 info = <table> {
 }
 updateTooltipTimer = 0
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = WeakAurasTooltipStatusBar {
 }
 GetUnit = <function> defined @Interface/FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantCostItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetItemInteractionItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextRight1 = WeakAurasTooltipTextRight1 {
 }
 SetRecipeReagentItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetEnhancedConduit = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAchievementByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 BottomOverlay = Texture {
 }
 SetSpellByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 supportsDataRefresh = true
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:293
 NineSlice = Frame {
 }
 SetInventoryItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 RefreshData = <function> defined @Interface/FrameXML/GameTooltip.lua:933
 SetTransmogrifyItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:990
 SetAction `

**Comment by mynian** [comment]
What kind of weakauras are you using?

I don't get any errors related to weakauras

**Comment by mynian** [comment]
I've tried testing with a couple of different weakauras that produce tooltips. I can't seem to reproduce.

**Comment by BlueNightSky** [comment]
I don't know which WA is caused by it. Too much weakauras. ignoring this error first, thank you for updating!

**Comment by mynian** [comment]
My guess is that there is a WA that is using some kind of weird method to produce some kind of tooltip.

 If anyone else gets this kind of error and can narrow it down to a specific WA, first make sure that it was updated post 10.0.2 to use the new tooltip functions, and if it was and you are still getting this error, please link the WA here so I can actually reproduce the error and attempt to find a way to bypass it as currently I have no way to try and figure out how to stop it without getting the error.

**Comment by BlueNightSky** [comment]
A new error occurred, I suspect that there is a conflict with TipTac? [https://www.curseforge.com/wow/addons/tiptac-reborn](url)
`55x Interface/AddOns/ConvertRatings/ConvertRatings.lua:295: attempt to index a nil value
[string "@Interface/AddOns/ConvertRatings/ConvertRatings.lua"]:295: in function <Interface/AddOns/ConvertRatings/ConvertRatings.lua:228>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
[string "@Interface/SharedXML/Tooltip/TooltipDataHandler.lua"]:449: in function <Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444>
[string "=[C]"]: in function `SetLootItem'
[string "@Interface/FrameXML/LootFrame.lua"]:330: in function <Interface/FrameXML/LootFrame.lua:319>
[string "=(tail call)"]: ?

Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetTraitEntry = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @Interface/FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @Interface/FrameXML/GameTooltip.lua:990
 ttGradient = Texture {
 }
 SetQuestLogSpecialItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 TopRightCorner = Texture {
 }
 ttLastUpdate = 0
 SetSocketedRelic = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 OnLoad = <function> defined @Interface/FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @Interface/AddOns/TipTac/ttCore.lua:1732
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 ttDisplayingUnit = false
 SetArtifactPowerByID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:344
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @Interface/FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:303
 ttWorkaroundForFirstMouseoverStatus = 0
 SetPvpTalent = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight1Font = "GameTooltipHeaderText"
 ttSetBackdropBorderColorLocked = true
 SetInfoBackdropStyle = <function> defined @Interface/SharedXML/Tooltip/TooltipDataHandler.lua:338
 GetBackdropBorderColor = <func`

**Comment by mynian** [comment]
Its not tiptac. I logged into my test character, Loaded only my addon, WA and tiptac and received no errors and everything functioned as expected.

**Comment by MadBubble** [comment]
I have a similar error and found which WA triggers it for me, it was weapon enchant tracker for shaman. This is the WA:
https://wago.io/KyN_MPsKd
It triggers on initiation and every time you use enchants (trigger updates i assume)

**Comment by mynian** [comment]
Thank you for that.

I was finally able to reproduce the error and I think I nabbed the culprit.

**Comment by mynian** [comment]
I just pushed v2.3.1 out. Let me know if the error persists or if anything new pops up.

**Comment by BlueNightSky** [comment]
> I just pushed v2.3.1 out. Let me know if the error persists or if anything new pops up.

The latest version will no longer appear lua errors, it's great!
