### ISSUE TITLE
Lua error!

### ISSUE THREAD

**Issue by BlueNightSky** [mynian/ConvertRatings#44]
I often have the following errors during the upgrade process:

`12x ConvertRatings/ConvertRatings.lua:295: attempt to index a nil value
[string "@ConvertRatings/ConvertRatings.lua"]:295: in function <ConvertRatings/ConvertRatings.lua:228>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:282: in function <SharedXML/Tooltip/TooltipDataHandler.lua:240>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:237: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `ProcessInfo'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:449: in function <SharedXML/Tooltip/TooltipDataHandler.lua:444>
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1504: in function `OnUpdate'
[string "@FrameXML/ContainerFrame.lua"]:1471: in function `OnEnter'
[string "@Inventorian/Item.lua"]:302: in function <Inventorian/Item.lua:286>

Locals:
self = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ItemTooltip = Frame {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetAzeriteEssence = <function> defined =[C]:-1
 ttBackdropBorderColorApplied = false
 SetTraitEntry = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ClearBackdrop = <function> defined @SharedXML/Backdrop.lua:282
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined =[C]:-1
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 ttGradient = Texture {
 }
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 TopRightCorner = Texture {
 }
 ttLastUpdate = 0
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined =[C]:-1
 NineSlice = Frame {
 }
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 TopEdge = Texture {
 }
 SetUnitDebuffByAuraInstanceID = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 SetBackdropColor = <function> defined @TipTac/ttCore.lua:1771
 LeftEdge = Texture {
 }
 AddLineDataText = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:324
 SetSpellBookItem = <function> defined =[C]:-1
 textLeft1Font = "GameTooltipHeaderText"
 SetShapeshift = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ttDisplayingUnit = false
 SetArtifactPowerByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 SetSocketedItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuff = <function> defined =[C]:-1
 SetMountBySpellID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBorderBlendMode = <function> defined @SharedXML/Backdrop.lua:266
 SetTrainerService = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 TextLeft1 = GameTooltipTextLeft1 {
 }
 GetTooltipData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:344
 SetLFGDungeonShortageReward = <function> defined =[C]:-1
 OnBackdropSizeChanged = <function> defined @SharedXML/Backdrop.lua:182
 SetArtifactItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 StatusBar = GameTooltipStatusBar {
 }
 SetPossession = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 statusBarPool = <table> {
 }
 SetUnitAura = <function> defined =[C]:-1
 SetUnitBuffByAuraInstanceID = <function> defined =[C]:-1
 SetConduit = <function> defined =[C]:-1
 SetupPieceVisuals = <function> defined @SharedXML/Backdrop.lua:246
 SetMinimapMouseover = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetItem = <function> defined @FrameXML/GameTooltip.lua:986
 SetRecipeResultItem = <function> defined =[C]:-1
 SetQuestPartyProgress = <function> defined =[C]:-1
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 ttWorkaroundForFirstMouseoverStatus = 0
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetExistingSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined =[C]:-1
 SetTotem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ttSetBackdropBorderColorLocked = true
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 textRight1Font = "GameTooltipHeaderText"
 `

**Comment by mynian** [comment]
do you have an addon called Inventorian installed? Because it looks like that addon is passing bad info

**Comment by BlueNightSky** [comment]
> do you have an addon called Inventorian installed? Because it looks like that addon is passing bad info

Yes, I installed Inventorian. :-P
