### ISSUE TITLE
Double numbers

### ISSUE THREAD

**Issue by Zasz333** [mynian/ConvertRatings#45]
On rings and weapons the values for secondary stats are displayed twice.

**Comment by mynian** [comment]
Not a bug, a feature. They would show different values if replacing one ring or weapon would result in that particular stat reaching a different diminishing returns breakpoint.

**Comment by Zasz333** [comment]
Is there a way to disable this? Optional of course. Because having this only on rings and weapons seems kind of useless.

**Comment by mynian** [comment]
Not the way I have it coded. It only appears on rings and 1h weapons (it should show on trinkets too if they have secondary stats as a static stat) because those slots are the only spots where you can have two of the same type of item equipped.
