### ISSUE TITLE
Use BigWigs Packager so Releases Can Be Used By Addon Managers

### ISSUE THREAD

**Issue by srhinos** [mynian/ConvertRatings#46]
Heya, I use WoWUp to manage my addons and mostly avoid curseforge but noticed the releases aren't being bundled in a way thats friendly to WoWUp.

Happy to contribute the BigWigs Packager config to make this work (at least for automating github side of things) but figured I'd raise it in case this isn't on your radar yet!

**Comment by mynian** [comment]
I looked into something like that initially, but it confused the hell out of me so I've just been using the curseforge webhook to pull automatically when i publish a release. I then download the zip from cf and upload it manually to wowi and wago.

**Comment by mynian** [comment]
I think I did it. Not 100% though. For some reason the packager put all kinds of fancy stuff in the release when i tested it on my other addon, but not for this one. It may have had something to do with me having to attempt it like 5000 times for this addon as for some reason the packager was telling me to go fuck myself and not publishing anything until i did a second release tag.
