### ISSUE TITLE
Coversion Percentages Displaying Twice

### ISSUE THREAD

**Issue by swisherjason** [mynian/ConvertRatings#48]
For Ring, Trinket, and Weapon slots, the percentages display twice in the tooltip:
![image](https://github.com/mynian/ConvertRatings/assets/39735724/d2b07f0b-c8c8-4767-afd2-8d7126d15ff0)
![image](https://github.com/mynian/ConvertRatings/assets/39735724/9749b325-96cd-4579-b00a-582be39c3f91)
![image](https://github.com/mynian/ConvertRatings/assets/39735724/58fadfeb-b4fa-489b-ab28-45aaf6c43847)

Nothing is breaking the addon in-game; just something for a future update to consider.

**Comment by mynian** [comment]
Not a bug, it's for each individual slot.
