### ISSUE TITLE
TWW Prepatch Error

### ISSUE THREAD

**Issue by EloMoose** [mynian/ConvertRatings#50]
Getting the below error when loading into game

23x ConvertRatings/ConvertRatings.lua:156: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@ConvertRatings/ConvertRatings.lua"]:156: in main chunk

> Locals:
colorTable = <table> {
 light red = <table> {
 }
 blue = <table> {
 }
 light blue = <table> {
 }
 pink = <table> {
 }
 default = <table> {
 }
 black = <table> {
 }
 green = <table> {
 }
 white = <table> {
 }
 purple = <table> {
 }
 orange = <table> {
 }
 red = <table> {
 }
}
cvrpanel = Frame {
 name = "Convert Ratings"
}
cvropttitle = ARTWORK {
}
cvrddtitle = ARTWORK {
}
cvrdropdown = CVRDropDown {
 Right = CVRDropDownRight {
 }
 Left = CVRDropDownLeft {
 }
 Text = CVRDropDownText {
 }
 Button = CVRDropDownButton {
 }
 Icon = CVRDropDownIcon {
 }
 Middle = CVRDropDownMiddle {
 }
 noResize = 1
}
cvrddtitle = ARTWORK {
}
cvrbutton = Button {
 Right = Texture {
 }
 Left = Texture {
 }
 fitTextWidthPadding = 40
 Text = TopText {
 }
 Middle = Texture {
 }
 fitTextCanWidthDecrease = true
}
(*temporary) = nil
(*temporary) = Frame {
 name = "Convert Ratings"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by mynian** [comment]
Guess they changed some stuff dealing with the options panel. I'll see what I can do, but I don't currently have an active subscription.

Edit: Apparently my sub is still active. Should help with debugging.

**Comment by mynian** [comment]
The latest release has some temp fixes that allow the addon to run. In order to do so I had to remove the options panel and removed the color picker. You can still change the color of the text via slash commands.
