### ISSUE TITLE
ConvertRatings.lua:460: attempt to call global 'GetItemStats' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [mynian/ConvertRatings#52]
Update to 11.0.2 seems have caused the addon to produce errors when mousing over an item. I assume some variable changed. Thanks.

283x ConvertRatings/ConvertRatings.lua:460: attempt to call global 'GetItemStats' (a nil value)
[string "@ConvertRatings/ConvertRatings.lua"]:460: in function <ConvertRatings/ConvertRatings.lua:368>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
...
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Pawn/Pawn.lua"]:2143: in function `PawnGetStatsFromTooltipWithMethod'
[string "@Pawn/Pawn.lua"]:1384: in function `PawnGetItemData'
[string "@Pawn/Pawn.lua"]:1625: in function `PawnGetItemDataForInventorySlot'
[string "@Pawn/Pawn.lua"]:3852: in function `PawnCheckInventoryForUpgrades'
[string "@Pawn/Pawn.lua"]:4152: in function <Pawn/Pawn.lua:4144>
[string "@Pawn/VgerCore/VgerCore.lua"]:356: in function `PawnOnInventoryChanged'
[string "@Pawn/Pawn.lua"]:140: in function `PawnOnEvent'
[string "*PawnUI.xml:1653_OnEvent"]:1: in function <[string "*PawnUI.xml:1653_OnEvent"]:1>

Locals:
self = AltoScanningTooltip {
 CIMI_tooltipWritten = true
 hasMoney = 1
 shownMoneyFrames = 1
 numMoneyFrames = 1
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 StatusBar = AltoScanningTooltipStatusBar {
 }
 TextRight1 = AltoScanningTooltipTextRight1 {
 }
 supportsDataRefresh = true
 textRight1Font = "GameTooltipHeaderText"
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 layoutType = "TooltipDefaultLayout"
 TextLeft1 = AltoScanningTooltipTextLeft1 {
 }
 textLeft2Font = "GameTooltipText"
 TextRight2 = AltoScanningTooltipTextRight2 {
 }
 TextLeft2 = AltoScanningTooltipTextLeft2 {
 }
}
itemGuid = nil
itemLink = "|cffa335ee|Hitem:204395::::::::70:253:::::::::|h[Hydratooth Girdle]|h|r"
rawcrit = nil
rawhaste = nil
rawmastery = nil
rawvers = nil
stats = nil
rawleech = nil
rawavoid = nil
rawspeed = nil
hexcolor = nil
oldmastery = nil
newsomastery = nil
newstmastery = nil
oldcrit = nil
newsocrit = nil
newstcrit = nil
oldhaste = nil
newsohaste = nil
newsthaste = nil
oldvers = nil
newsovers = nil
newstvers = nil
oldavoid = nil
newsoavoid = nil
newstavoid = nil
oldspeed = nil
newsospeed = nil
newstspeed = nil
oldleech = nil
newsoleech = nil
newstleech = nil
eqitemslot = nil
eqitemslotname = nil
eqitemtype = nil
eqsoitemlink = nil
eqstitemlink = nil
eqsostats = nil
eqststats = nil
eqsomastery = nil
eqstmastery = nil
eqsocrit = nil
eqstcrit = nil
eqsohaste = nil
eqsthaste = nil
eqsovers = nil
eqstvers = nil
eqsoleech = nil
eqstleech = nil
eqsoavoid = nil
eqstavoid = nil
eqsospeed = nil
eqstspeed = nil
stitemtype = nil
stitemslot = nil
stitemlink = nil
numServices = 0
(*temporary) = nil
(*temporary) = "|cffa335ee|Hitem:204395::::::::70:253:::::::::|h[Hydratooth Girdle]|h|r"
(*temporary) = "attempt to call global 'GetItemStats' (a nil value)"
cvlevel = 70
masteryamt = 185.299994
hasteamt = 174.711423
critamt = 185.299994
leechamt = 270.007272
avoidamt = 144.003878
speedamt = 45.001212
invtable = <table> {
 1 = 1
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
 9 = 9
 10 = 10
 11 = 11
 12 = 13
 13 = 16
 14 = 17
 15 = 16
 16 = 15
 17 = 16
 18 = 0
 19 = 0
 20 = 5
 21 = 16
 22 = 17
 23 = 17
 24 = 0
 25 = 0
 26 = 16
 27 = 0
 28 = 0
}

**Comment by skjetne** [comment]
Same error if it helps

```25x ConvertRatings/ConvertRatings.lua:460: attempt to call global 'GetItemStats' (a nil value)
[string "@ConvertRatings/ConvertRatings.lua"]:460: in function <ConvertRatings/ConvertRatings.lua:368>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:61: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:56>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:81: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:77>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:117: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:107>
[string "=[C]"]: in function `SetAttribute'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:142: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:135>
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:288: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:238>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua"]:235: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:234>
[string "=(tail call)"]: ?
[string "@Blizzard_MailFrame/MailFrame.lua"]:347: in function `InboxFrameItem_OnEnter'
[string "*MailFrame.xml:154_OnEnter"]:1: in function <[string "*MailFrame.xml:154_OnEnter"]:1>

Locals:
self = GameTooltip {
 ItemTooltip = Frame {
 }
 BottomOverlay = Texture {
 }
 NineSlice = Frame {
 }
 textLeft1Font = "GameTooltipHeaderText"
 textRight2Font = "GameTooltipText"
 TopOverlay = Texture {
 }
 TextLeft1 = GameTooltipTextLeft1 {
 }
 StatusBar = GameTooltipStatusBar {
 }
 supportsItemComparison = true
 supportsDataRefresh = true
 processingInfo = <table> {
 }
 infoList = <table> {
 }
 waitingForData = false
 shoppingTooltips = <table> {
 }
 updateTooltipTimer = 0.138000
 TextRight1 = GameTooltipTextRight1 {
 }
 textRight1Font = "GameTooltipHeaderText"
 layoutType = "TooltipDefaultLayout"
 textLeft2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
}
itemGuid = nil
itemLink = "|cffffffff|Hitem:40110::::::::70:255:::::::::|h[Haunted Memento]|h|r"
rawcrit = nil
rawhaste = nil
rawmastery = nil
rawvers = nil
stats = nil
rawleech = nil
rawavoid = nil
rawspeed = nil
hexcolor = nil
oldmastery = nil
newsomastery = nil
newstmastery = nil
oldcrit = nil
newsocrit = nil
newstcrit = nil
oldhaste = nil
newsohaste = nil
newsthaste = nil
oldvers = nil
newsovers = nil
newstvers = nil
oldavoid = nil
newsoavoid = nil
newstavoid = nil
oldspeed = nil
newsospeed = nil
newstspeed = nil
oldleech = nil
newsoleech = nil
newstleech = nil
eqitemslot = nil
eqitemslotname = nil
eqitemtype = nil
eqsoitemlink = nil
eqstitemlink = nil
eqsostats = nil
eqststats = nil
eqsomastery = nil
eqstmastery = nil
eqsocrit = nil
eqstcrit = nil
eqsohaste = nil
eqsthaste = nil
eqsovers = nil
eqstvers = nil
eqsoleech = nil
eqstleech = nil
eqsoavoid = nil
eqstavoid = nil
eqsospeed = nil
eqstspeed = nil
stitemtype = nil
stitemslot = nil
stitemlink = nil
numServices = 0
(*temporary) = nil
(*temporary) = "|cffffffff|Hitem:40110::::::::70:255:::::::::|h[Haunted Memento]|h|r"
(*temporary) = "attempt to call global 'GetItemStats' (a nil value)"
cvlevel = 70
masteryamt = 185.299994
hasteamt = 174.711423
critamt = 185.299994
leechamt = 270.007272
avoidamt = 144.003878
speedamt = 45.001212
invtable = <table> {
 1 = 1
 2 = 2
 3 = 3
 4 = 4
 5 = 5
 6 = 6
 7 = 7
 8 = 8
 9 = 9
 10 = 10
 11 = 11
 12 = 13
 13 = 16
 14 = 17
 15 = 16
 16 = 15
 17 = 16
 18 = 0
 19 = 0
 20 = 5
 21 = 16
 22 = 17
 23 = 17
 24 = 0
 25 = 0
 26 = 16
 27 = 0
 28 = 0
}
```

**Comment by mynian** [comment]
should be fixed in latest release.

They changed the function needed to pull the stats table from items to their updated naming schema.
